/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratamentoRouteImport } from './routes/tratamento'
import { Route as MissaoRouteImport } from './routes/missao'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoAjudarRouteImport } from './routes/como-ajudar'
import { Route as IndexRouteImport } from './routes/index'

const TratamentoRoute = TratamentoRouteImport.update({
  id: '/tratamento',
  path: '/tratamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoRoute = MissaoRouteImport.update({
  id: '/missao',
  path: '/missao',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAjudarRoute = ComoAjudarRouteImport.update({
  id: '/como-ajudar',
  path: '/como-ajudar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/missao': typeof MissaoRoute
  '/tratamento': typeof TratamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/missao': typeof MissaoRoute
  '/tratamento': typeof TratamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/missao': typeof MissaoRoute
  '/tratamento': typeof TratamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-ajudar'
    | '/contato'
    | '/depoimentos'
    | '/equipe'
    | '/galeria'
    | '/missao'
    | '/tratamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-ajudar'
    | '/contato'
    | '/depoimentos'
    | '/equipe'
    | '/galeria'
    | '/missao'
    | '/tratamento'
  id:
    | '__root__'
    | '/'
    | '/como-ajudar'
    | '/contato'
    | '/depoimentos'
    | '/equipe'
    | '/galeria'
    | '/missao'
    | '/tratamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoAjudarRoute: typeof ComoAjudarRoute
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  EquipeRoute: typeof EquipeRoute
  GaleriaRoute: typeof GaleriaRoute
  MissaoRoute: typeof MissaoRoute
  TratamentoRoute: typeof TratamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratamento': {
      id: '/tratamento'
      path: '/tratamento'
      fullPath: '/tratamento'
      preLoaderRoute: typeof TratamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao': {
      id: '/missao'
      path: '/missao'
      fullPath: '/missao'
      preLoaderRoute: typeof MissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar': {
      id: '/como-ajudar'
      path: '/como-ajudar'
      fullPath: '/como-ajudar'
      preLoaderRoute: typeof ComoAjudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoAjudarRoute: ComoAjudarRoute,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  EquipeRoute: EquipeRoute,
  GaleriaRoute: GaleriaRoute,
  MissaoRoute: MissaoRoute,
  TratamentoRoute: TratamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
